apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stables.foo.com
spec:
  group: foo.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                prop: { type: string }
      subresources:
        status: {}
  names:
    kind: Stable
    listKind: StableList
    plural: stables
    singular: stable
  scope: Namespaced
