apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.instana.com
spec:
  group: instana.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name: { type: string }
                provider: { type: string }
      subresources:
        status: {}
  names:
    kind: DataStore
    listKind: DataStoreList
    plural: datastores
    singular: datastore
  scope: Namespaced