apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datastoreaccessclaims.instana.com
spec:
  group: instana.com
  names:
    kind: DataStoreAccessClaim
    listKind: DataStoreAccessClaimList
    plural: datastoreaccessclaims
    singular: datastoreaccessclaim
  scope: Namespaced
  version: v1alpha1