apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastoreaccessclaims.instana.com
spec:
  group: instana.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                roles:
                  type: array
                  items: { type: string }
                dataStoreSelector: 
                  type: object
                  properties:
                    matchName: { type: string }
                secretSelector: 
                  type: object
                  properties:
                    matchName: { type: string }
            status:
              type: object
              properties:
                conditions:
                  description: List of status conditions to indicate the status of a
                    CertificateRequest. Known condition types are `Ready` and `InvalidRequest`.
                  items:
                    description: CertificateRequestCondition contains condition information
                      for a CertificateRequest.
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the timestamp corresponding
                          to the last status change of this condition.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human readable description of the
                          details of the last transition, complementing reason.
                        type: string
                      reason:
                        description: Reason is a brief machine readable explanation
                          for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of ('True', 'False',
                          'Unknown').
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        description: Type of the condition, known values are ('Ready',
                          'InvalidRequest').
                        type: string
                    required:
                    - status
                    - type
                    type: object
                  type: array
      subresources:
        status: {}
  names:
    kind: DataStoreAccessClaim
    listKind: DataStoreAccessClaimList
    plural: datastoreaccessclaims
    singular: datastoreaccessclaim
  scope: Namespaced
