apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-example
spec:
  selector:
    matchLabels:
      app: operator-example
  replicas: 1
  template:
    metadata:
      labels:
        app: operator-example
    spec:
      serviceAccountName: operator-example
      containers:
      - image: registry:5000/claude/operator-jvm
        name: operator
        imagePullPolicy: Always