apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-example
spec:
  selector:
    matchLabels:
      app: operator-example
  replicas: 1
  template:
    metadata:
      labels:
        app: operator-example
    spec:
      serviceAccountName: operator-example
      containers:
      - image: k3s/a-operator
        name: operator
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"