apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-example
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups:
  - instana.com
  resources:
  - datastores
  - datastores/status
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "put"]
- apiGroups:
  - instana.com
  resources:
  - datastoreaccessclaims
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]